- name: Pull image from DockerHub repository
  docker_image:
    name: allanbinga/yolo-backend:v1.0.0
    source: pull

- name: Create a nodejs server container.
  docker_container:
    name: yolo-backend
    image: allanbinga/yolo-backend:v1.0.0
    networks:
      - name: yolo-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes