version: "3.8"

services:
  allanbinga-yolo-client:
    image: allanbinga/yolo-client:v1.0.0
    build: ./client
    container_name: yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - allanbinga-yolo-backend
    networks:
      - yolo-net
  
  allanbinga-yolo-backend:
    image: allanbinga/yolo-backend:v1.0.0
    build: ./backend
    container_name: yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - app-ip-mongo
    networks:
      - yolo-net
  
  app-ip-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - yolo-net
    volumes:
      - type: volume
        source: app-mongo-data
        target: /data/db

networks:
  yolo-net:
    external: true  

volumes:
  app-mongo-data:
    driver: local
