- name: Create Docker network
  docker_network:
    name: yolo-net
    state: present
    
- name: Run MongoDB Container
  docker_container:
    name: app-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./app-mongo-data:/data/db
    networks:
      - name: yolo-net
  tags:
    - database
    - backend